
services:
  redis:
    image: redis:7.2.3
    ports:
      - "6379:6379"

  celery:
    build: .
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    ports:
      - "80:80"
    restart: always
