name: Trigger auto deployment for testcerlyphyton

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/testcerlyphyton-AutoDeployTrigger-ac26dc6c-b6e2-4fff-98c8-37b2b27afd4c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TESTCERLYPHYTON_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TESTCERLYPHYTON_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TESTCERLYPHYTON_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.TESTCERLYPHYTON_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TESTCERLYPHYTON_REGISTRY_PASSWORD }}
          containerAppName: testcerlyphyton
          resourceGroup: v-bodaharish-rg
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


